Repository apache/airavata, pull requests merged in 2025-06, with the labels that each got.

#507 docs: Update README files with modern formatting and Java 17
  README.md
  modules/ide-integration/README.md
Labels: docs

#512 Add Plugin for Consistent Code Styling and License Headers
  apache-license-header-java.txt
  apache-license-header-xml.txt
  modules/commons/src/main/java/org/apache/airavata/common/utils/ServiceUtils.java
  modules/messaging/core/src/main/java/org/apache/airavata/messaging/core/PublisherFactory.java
  modules/messaging/core/src/main/java/org/apache/airavata/messaging/core/impl/RabbitMQProcessLaunchConsumer.java
  modules/messaging/core/src/main/java/org/apache/airavata/messaging/core/impl/RabbitMQProcessLaunchPublisher.java
  modules/messaging/core/src/main/java/org/apache/airavata/messaging/core/impl/RabbitMQProducer.java
  modules/messaging/core/src/main/java/org/apache/airavata/messaging/core/impl/RabbitMQStatusPublisher.java
  modules/messaging/core/src/main/java/org/apache/airavata/messaging/core/impl/RabbitMQStatusSubscriber.java
  modules/orchestrator/orchestrator-core/src/test/java/org/apache/airavata/orchestrator/core/ValidatorTest.java
  modules/orchestrator/orchestrator-core/src/test/java/org/apache/airavata/orchestrator/core/util/SecondValidator.java
  modules/orchestrator/orchestrator-core/src/test/java/org/apache/airavata/orchestrator/core/util/TestValidator.java
  pom.xml
Labels: enhancement, java

#517 Agent Framework Refactoring - Fix build issues
  modules/agent-framework/agent-service/pom.xml
  modules/agent-framework/pom.xml
  pom.xml
Labels: bug, enhancement

#518 Add details about the airavata ecosystem into README.md
  README.md
Labels: docs

#520 Support better text search
  modules/research-framework/portal/src/components/home/ResourceCard.tsx
  modules/research-framework/portal/src/components/resources/index.tsx
  modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/controller/ResourceController.java
  modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/handlers/ResourceHandler.java
  modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/repo/ResourceRepository.java
  modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/repo/TagRepository.java
Labels: enhancement, javascript
